### ISSUE TITLE
License

### ISSUE THREAD

**Issue by silkentrance** [tusharvjoshi/NBDrupalDevel#43]
Now that NetBeans is submitted to the apache foundation and will enter incubation there soon, the overall licensing scheme of netbeans will be changed to the Apache License 2.0.

Existing dependencies towards non CDDT/LGPL licensed components will be eliminated in that process, moving everything to the same Apache License 2.0 while retaining the LGPL license of external components.

How about changing the license of this also to the Apache License 2.0?

**Comment by tusharjoshi** [comment]
I totally agree with you here.  I believe providing the existing release with GPL license and newer once with new Apache v2 is acceptable.

I will change the license to Apache v2.

**Comment by Chris2011** [comment]
Sry folks but why is it needed to switch to the apache license for independent plugins? they havn't anything todo with the NetBeans going to apache license. Because the plugins are not working under the contributing license stuff. All my plugins has the MIT license and I don't have to change it. Only my opinion.

**Comment by tusharjoshi** [comment]
I agree that independent plugins may not switch licenses just because main NetBeans switched it to Apache v2.  The switch made here was in anticipation that it will become same license as Apache NetBeans.  Another thing is to switch the license to something other than GPL, MIT is a good choice Apache v2 is one of the choices.

We still do not know what will be the requirements for a Apache NetBeans Plugin portal when it will be active, and this license may help that time also to publish this plugin with that portal.

The release available v2.0.11 will still remain with its original license though that is GPLv2.

**Comment by Chris2011** [comment]
Thx for your explanation.
